### ISSUE TITLE
continuous reboot 

### ISSUE THREAD

**Issue by bencao74** [MiSTer-devel/Arcade-Xevious_MiSTer#2]
Hey, 

 the xevious core with rom fires continuous reboot. 

Could you help me?

Cheers

**Comment by bencao74** [comment]
For information I used rom set 0.37b5

I think it's a rom check cycle causing this behavior. 

Which rom set is recommended to use? 0.106 like advmame or higher?

**Comment by sorgelig** [comment]
I don't remember, unfortunately. Ask on Atari forum - may be you will get useful answer there.

**Comment by the1ross** [comment]
I'm having the same issue.

**Comment by hubertbanas** [comment]
See [this](http://www.atari-forum.com/viewtopic.php?f=117&t=32481&start=200#p356406) post

**Comment by sorgelig** [comment]
should be fixed with correct rom
