### ISSUE TITLE
CRT H-sync adjust option conflicts with Pause and Autosave Hiscores options

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/Arcade-Xevious_MiSTer#25]
Changing values of CRT H-Sync adjust option also affects the values related to Pause and Hiscore autosave options (and vice versa). Observed in both regular Xevious and Super Xevious.

**Comment by sorgelig** [comment]
fixed in new release

**Comment by Thelypody** [comment]
Excellent, thanks!
